Portfolio:Desktop version
Cheptoo21/Project-Portfolio pull request #1
Opened 2023-06-28 08:13 UTC by Cheptoo21

In this Project:

- I used media query to make my portfolio responsive.
- I added contact form.
- I implemented desktop version of the portfolio.
- I deployed my project using github pages.

2023-06-30 17:03 UTC, nicupop729 requested changes
Hello @Cheptoo21  👋,

_This is an manual review._

Please review the inline comments provided for improvement suggestions to ensure the approval of these two milestones. 
Once you have made the necessary changes, kindly request another review.

Keep rocking 🚀!

2023-06-30 17:03 UTC, nicupop729 commented on index.html
> +                        <input name="user_Name" type="text" maxlength="30" placeholder="Full Name" >
As specified in the project requirements, it is stated that a user should not be unable to submit the form if any of the fields are left empty. However, in this particular case, I was able to submit the form without entering a name, which is something we need to address.

- [ ] Kindly ensure that inputting the name becomes a mandatory requirement for form submission.

2023-06-30 17:03 UTC, nicupop729 commented on index.html
> +    </div>
The background images should always be introduced through the CSS file and never through the index.html file, to follow the best practices.
in this case, in the mobile view, it creates a big white space between the form and the social media icons.
https://www.loom.com/share/a56a46d2cf4d4ce49f09fae3f9593e29?sid=0d0b4c24-4477-4f7a-bf6e-a0d5d5b0e46c

- [ ] Kindly make sure to remove the white space between the form and the social media icons.
- [ ] Let's also ensure that we introduce the background images through the CSS file and not through the index.html file.

[Here is an article](https://www.w3docs.com/snippets/html/when-to-use-html-img-tag-and-css-background-image-property.html#:~:text=In%20general%2C%20use%20the%20%3Cimg,for%20decorative%20or%20design%20purposes.) about how to introduce the background images through CSS file and not HTML file.

2023-07-05 07:43 UTC, Cheptoo21 commented
Hello  ***@***.****
I hope this email finds you well.
Here is the link to my PR with the requested changes:
https://github.com/Cheptoo21/Project-Portfolio/pull/1.
Looking forward to the approval.
Thank you.

On Fri, Jun 30, 2023 at 8:03 PM Nicolae Pop ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @Cheptoo21 <https://github.com/Cheptoo21> 👋,
>
> *This is an manual review.*
>
> Please review the inline comments provided for improvement suggestions to
> ensure the approval of these two milestones.
> Once you have made the necessary changes, kindly request another review.
>
> Keep rocking 🚀!
> ------------------------------
>
> In index.html
> <https://github.com/Cheptoo21/Project-Portfolio/pull/1#discussion_r1248066657>
> :
>
> > +                </ul>
> +            </div>
> +        </div>
> +    </section>
> +
> +    <section id="contact" class="contact">
> +        <div class="heading">
> +            <h3>
> +                I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.
> +            </h3>
> +        </div>
> +        <div class="form">
> +            <form action="https://formspree.io/f/xayzredb" method="POST">
> +                <ul>
> +                    <li>
> +                        <input name="user_Name" type="text" maxlength="30" placeholder="Full Name" >
>
> As specified in the project requirements, it is stated that a user should
> be unable to submit the form if any of the fields are left empty. However,
> in this particular case, I was able to submit the form without entering a
> name, which is something we need to address.
>
>    - Kindly ensure that inputting the name becomes a mandatory
>    requirement for form submission.
>
> ------------------------------
>
> In index.html
> <https://github.com/Cheptoo21/Project-Portfolio/pull/1#discussion_r1248093029>
> :
>
> > +    <div class="background">
> +        <img class="Background_img1" src="frames/form1.png" alt="Img 1">
> +        <img class="Background_img2" ***@***.***" alt="Img 2">
> +        <img class="Background_img3" src="frames/form.png" alt="Img 3">
> +
> +    </div>
>
> The background images should always be introduced through the CSS file and
> never through the index.html file, to follow the best practices.
> in this case, in the mobile view, it creates a big white space between the
> form and the social media icons.
>
> https://www.loom.com/share/a56a46d2cf4d4ce49f09fae3f9593e29?sid=0d0b4c24-4477-4f7a-bf6e-a0d5d5b0e46c
>
>    - Kindly make sure to remove the white space between the form and the
>    social media icons.
>    - Let's also ensure that we introduce the background images through
>    the CSS file and not through the index.html file.
>
> Here is an article
> <https://www.w3docs.com/snippets/html/when-to-use-html-img-tag-and-css-background-image-property.html#:~:text=In%20general%2C%20use%20the%20%3Cimg,for%20decorative%20or%20design%20purposes.>
> about how to introduce the background images through CSS file and not HTML
> file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Cheptoo21/Project-Portfolio/pull/1#pullrequestreview-1507522620>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWX3OLRTX7DZRMN4J54XVLTXN4BHDANCNFSM6AAAAAAZWVG4TM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-07 11:47 UTC, bellom commented
Hi @Cheptoo21,

### This is a manual review

# Approve :+1:
Cheers and Happy coding!:clap::clap::clap:

2023-07-07 12:03 UTC, bellom commented
@Cheptoo21 - kindly go ahead and merge so that we can continue the process.

2023-07-07 12:08 UTC, merged